edition = "2021"

# nightly `rustfmt` must be used for formatting.
unstable_features = true

comment_width = 100
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
normalize_comments = true
use_field_init_shorthand = true
wrap_comments = true
